### ISSUE TITLE
thanks very much!!

### ISSUE THREAD

**Issue by Luyakus** [ganeshrvel/mtp-nodejs-port#1]
I am do the same work as openmtp, thanks a lot for this extension, help me a lot

**Comment by ganeshrvel** [comment]
@Luyakus

The code in the main branch will block the event loop and because of this your app will freeze while a MTP function is being carried out. 

Check the "to-async" branch, it has functions written in an asynchronous way but unfortunately due to my limited understanding in C++ I had to pause the development in the "to-async" branch temporarily. 90% of the work is done but I need some help with the rest of the functions. If you are able to solve the problems please do share the code with the rest of us.

**Comment by Luyakus** [comment]
@ganeshrvel sorry, I am a iOS developer, also not familiar with c++,  but I believe you can do this. openmtp is an awesome app, trust yourself
